import type { ContentModeDefinition } from '../../core/registries/types.js';

export const advisoryMode: ContentModeDefinition = {
  id: 'advisory',
  name: 'Executive Advisory',
  description: 'Strategy decks, executive briefs, roadmaps, and recommendations',
  defaultFor: ['deck', 'brief', 'roadmap'],
  signals: {
    keywords: [
      'recommend',
      'strategy',
      'roadmap',
      'investment',
      'stakeholder',
      'business',
      'executive',
      'leadership',
      'outcome',
      'value',
      'ROI',
      'capability',
      'maturity',
      'assessment',
      'brief',
      'recommendation',
      'next steps',
      'action items',
      'I recommend',
      'my recommendation',
    ],
    audience: [
      'leadership',
      'executives',
      'stakeholders',
      'board',
      'C-suite',
      'VP',
      'director',
      'decision makers',
      'sponsors',
    ],
    structure: [
      /^#+\s*Executive Summary/im,
      /^#+\s*Recommendations?/im,
      /^#+\s*Next Steps/im,
      /^#+\s*Action Items/im,
      /^#+\s*Roadmap/im,
      /^#+\s*Strategic/im,
      /^#+\s*Assessment/im,
    ],
  },
};
