import type { ContentModeDefinition } from '../../core/registries/types.js';

export const architectureMode: ContentModeDefinition = {
  id: 'architecture',
  name: 'Solution Architecture',
  description: 'Technical architecture docs, ADRs, specs, and technical presentations',
  defaultFor: ['architecture', 'adr', 'tech-deck', 'spec'],
  signals: {
    keywords: [
      'system',
      'component',
      'data flow',
      'API',
      'deployment',
      'infrastructure',
      'architecture',
      'service',
      'database',
      'integration',
      'technical',
      'implementation',
      'specification',
      'container',
      'microservice',
      'endpoint',
      'schema',
      'diagram',
      'C4',
      'arc42',
      'ADR',
      'decision record',
    ],
    audience: [
      'engineers',
      'developers',
      'ops team',
      'technical team',
      'dev team',
      'architects',
      'platform team',
      'SRE',
      'DevOps',
    ],
    structure: [
      /^#+\s*System Context/im,
      /^#+\s*Container/im,
      /^#+\s*Component/im,
      /^#+\s*Deployment/im,
      /^#+\s*Building Blocks/im,
      /^#+\s*Runtime/im,
      /^#+\s*Decisions?/im,
      /^#+\s*ADR/im,
      /```mermaid/i,
      /```d2/i,
    ],
  },
};
