import type { ContentModeDefinition } from '../../core/registries/types.js';

export const documentationMode: ContentModeDefinition = {
  id: 'documentation',
  name: 'Documentation',
  description: 'User guides, tutorials, quick references, and technical documentation',
  defaultFor: ['guide', 'reference', 'tutorial'],
  signals: {
    keywords: [
      'how to',
      'step by step',
      'getting started',
      'installation',
      'install',
      'configure',
      'configuration',
      'setup',
      'usage',
      'guide',
      'tutorial',
      'reference',
      'documentation',
      'quick start',
      'quickstart',
      'prerequisites',
      'requirements',
      'example',
      'examples',
      'run the command',
      'follow these steps',
      'use the following',
      'to do this',
      'first, then',
      'user guide',
      'cheat sheet',
      'command reference',
      'options table',
      'parameter',
      'output format',
      'troubleshooting',
      'common issues',
      'FAQ',
    ],
    audience: [
      'users',
      'new users',
      'beginners',
      'developers using',
      'anyone looking to',
      'getting started',
      'first-time users',
      'end users',
      'all users',
      'target audience',
    ],
    structure: [
      /^#+\s*Getting Started/im,
      /^#+\s*Installation/im,
      /^#+\s*Prerequisites/im,
      /^#+\s*Configuration/im,
      /^#+\s*Usage/im,
      /^#+\s*Quick Start/im,
      /^#+\s*Examples?/im,
      /^#+\s*Commands?/im,
      /^#+\s*Options?/im,
      /^#+\s*Reference/im,
      /^#+\s*Troubleshooting/im,
      /^#+\s*FAQ/im,
      /^#+\s*Common Issues/im,
      /^#+\s*Step \d+/im,
      /^#+\s*\d+\.\s+\w/im,
      /```bash/i,
      /\|\s*Option\s*\|/i,
      /\|\s*Command\s*\|/i,
    ],
  },
};
